SELECT DISTINCT O.ANIMAL_ID, O.NAME #, I.DATETIME, O.DATETIME 
FROM ANIMAL_OUTS O, ANIMAL_INS I 
WHERE I.ANIMAL_ID = O.ANIMAL_ID AND I.DATETIME < O.DATETIME 
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC 
LIMIT 2