SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S INNER JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE BETWEEN '2022-01-00' AND '2022-02-00'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC


# SELECT BOOK_ID, SUM(SALES) FROM BOOK_SALES
# GROUP BY BOOK_ID