SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
WHERE CAR_TYPE = '세단' AND CAR_ID = ANY(
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE >= '2022-10-00' AND START_DATE < '2022-11-00' GROUP BY CAR_ID)
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
;